<?php $this->layout('default', [
    'title' => 'Layouts',
]); ?>

<?php $this->section('content') ?>
    <nav aria-label="You are here:" role="navigation">
        <ul class="breadcrumbs">
            <li><a href="<?= $this->pathFor('home') ?>">Home</a></li>
            <li><a href="<?= $this->pathFor('layouts') ?>">Layouts</a></li>
            <li><span class="show-for-sr">Current: </span> <?= $this->layout_->name ?></li>
        </ul>
    </nav>

    <form method="POST" action="<?= $this->pathFor('layouts_put', ['id' => $this->layout_->id]); ?>">
        <div class="row">
            <div class="medium-12 columns">
                <?= $this->insert('layouts/partials/layout_fields') ?>

                <input type="hidden" name="_METHOD" value="PUT">

                <div class="row">
                    <div class="medium-12 columns">
                        <button type="submit" class="button">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
<?php $this->replace() ?>
