<?php $this->layout('default', [
    'title' => 'Folders',
]); ?>

<?php $this->section('content') ?>
    <nav aria-label="You are here:" role="navigation">
        <ul class="breadcrumbs">
            <li><a href="<?= $this->pathFor('home') ?>">Home</a></li>
            <li><a href="<?= $this->pathFor('folders') ?>">Folders</a></li>
            <li><span class="show-for-sr">Current: </span> Publish</li>
        </ul>
    </nav>
<?php $this->replace() ?>
