<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->title ?></title>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic,700italic" media="screen" rel="stylesheet" type="text/css" >
    <link rel="stylesheet" type="text/css" href="/css/app.css">
    <?php $this->section('styles') ?>
    <?php $this->stop() ?>
</head>
<body>
    <nav class="topnav">
        <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
            <button class="menu-icon" type="button" data-toggle="example-menu"></button>
            <div class="title-bar-title">Menu</div>
        </div>
        <div class="top-bar" id="example-menu">
            <div class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu>
                    <li class="menu-text">Wordup</li>
                    <li><a href="<?= $this->pathFor('folders') ?>"><?= $this->translate('folders') ?></a></li>
                    <li>
                        <a href="#">Assets</a>
                        <ul class="menu vertical">
                            <li><a href="<?= $this->pathFor('content_types') ?>">Content Types</a></li>
                            <li><a href="#">Media Library</a></li>
                            <li><a href="#">Formatters</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Settings</a></li>
                </ul>
            </div>
            <div class="top-bar-right">
                <ul class="menu">
                    <li><input type="search" placeholder="Search"></li>
                    <li><button type="button" class="button">Search</button></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="large-12 columns">
            <?php if (isset($this->messages['success'])): ?>
                <div class="alert alert-success">
                    <?=$this->messages['success']; ?>
                </div>
            <?php endif; ?>

            <?php if (isset($this->messages['errors'])): ?>
                <div class="alert alert-danger alert-important">
                    <ul>
                        <?php foreach ($this->messages['errors'] as $error): ?>
                            <li><?= $error ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <?php $this->section('content') ?>
            <?php $this->stop() ?>
        </div>
    </div>

    <script src="/bower_components/jquery/dist/jquery.js"></script>
    <script src="/bower_components/what-input/dist/what-input.js"></script>
    <script src="/bower_components/foundation-sites/dist/js/foundation.js"></script>
    <script src="/js/app.js"></script>
    <?php $this->section('scripts') ?>
    <?php $this->stop() ?>
</body>
</html>
















<?php /*
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= $this->title ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->section('head') ?>
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic,700italic" media="screen" rel="stylesheet" type="text/css" >
        <link rel="stylesheet" type="text/css" href="/css/app.css">
    <?php $this->stop() ?>
</head>

<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->pathFor('home') ?>">SSOAuth</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <?php if ($this->currentUser): ?>
                        <li class="dropdown">
                            <form id="logout_form_navbar" method="post" action="<?= $this->pathFor('logout_post') ?>"><input type="hidden" name="_METHOD" value="DELETE"></form>

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?= $this->currentUser->first_name ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?= $this->pathFor('logout') ?>" onclick="$('form#delete_form').submit(); return false;"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                            </ul>
                        </li>
                    <?php else: ?>
                        <li><a href="<?= $this->pathFor('register') ?>"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                        <li><a href="<?= $this->pathFor('login') ?>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <?php if (isset($this->messages['success'])): ?>
            <div class="alert alert-success">
                <?=$this->messages['success']; ?>
            </div>
        <?php endif; ?>

        <?php if (isset($this->messages['errors'])): ?>
            <div class="alert alert-danger alert-important">
                <ul>
                    <?php foreach ($this->messages['errors'] as $error): ?>
                        <li><?= $error ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php $this->section('content') ?>
        <?php $this->stop() ?>
    </div>

    <?php $this->section('scripts') ?>
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script src="/js/app.js" type="text/javascript"></script>
    <?php $this->stop() ?>
</body>

</html>
*/ ?>
